# 💰 Funding & Sponsorship

# GitHub Sponsors
github: [saasyachtclub]

# Open Collective
open_collective: saas-yacht-club

# Ko-fi
ko_fi: saasyachtclub

# Buy Me a Coffee
custom: ["https://buymeacoffee.com/saasyachtclub", "https://saasyachtclub.com/sponsor"]
